# Generated by Django 4.2.3 on 2023-07-27 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_code', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_code', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255)),
                ('dept_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_test.dept')),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
