# Redis 공식 이미지를 기반으로 Docker 이미지 생성
FROM redis:latest

# 컨테이너 내부의 작업 디렉토리 설정 (선택사항)
WORKDIR /app

# Redis 서버를 실행하는 명령을 변경하거나 추가할 수 있습니다.
# 예를 들어, 설정 파일을 추가하거나 환경 변수를 설정할 수 있습니다.
# CMD ["redis-server"]

# Docker 컨테이너 내부에서 사용할 포트를 열어줍니다.
EXPOSE 6379
