# Generated by Django 4.2.3 on 2023-08-17 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("car_id", models.AutoField(primary_key=True, serialize=False)),
                ("manufacture_year", models.CharField(max_length=8)),
                ("registration_date", models.DateField()),
                ("brand", models.CharField(max_length=50)),
                ("car_type", models.CharField(max_length=50)),
                ("car_model", models.CharField(max_length=50)),
                ("car_color", models.CharField(max_length=20)),
                (
                    "fuel",
                    models.CharField(
                        choices=[
                            ("lpg", "lpg"),
                            ("gasoline", "휘발유"),
                            ("diesel", "디젤"),
                            ("hybrid", "하이브리드"),
                            ("electric", "전기"),
                            ("bifuel", "바이퓨얼"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("auto", "자동"), ("manual", "수동")], max_length=10
                    ),
                ),
                ("mileage", models.PositiveIntegerField()),
                ("region", models.CharField(max_length=50)),
                (
                    "car_status",
                    models.CharField(
                        choices=[
                            ("pending", "승인대기"),
                            ("auction", "경매진행"),
                            ("auction_closed", "경매종료"),
                            ("completed", "거래완료"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "car",
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="car.car"
                    ),
                ),
            ],
            options={
                "db_table": "image",
            },
        ),
    ]
