# Generated by Django 4.2.3 on 2023-08-17 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0003_alter_car_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
