# Generated by Django 4.2.3 on 2023-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0004_car_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="production_end",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="production_start",
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
