# Generated by Django 4.2.3 on 2023-08-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0005_car_production_end_car_production_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="auction_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
