# Generated by Django 4.2.3 on 2023-08-18 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0006_car_auction_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carimage",
            old_name="order",
            new_name="seq",
        ),
        migrations.AlterField(
            model_name="carimage",
            name="car",
            field=models.ForeignKey(
                db_column="car_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="car.car",
            ),
        ),
    ]
