# Generated by Django 4.2.3 on 2023-08-18 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0007_rename_order_carimage_seq_alter_carimage_car"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carimage",
            old_name="car",
            new_name="car_id",
        ),
    ]
