version: '3'
services:
  db:
    image: postgres:13
    env_file:
      - ./db.env
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test_PaaarkSH:/test_PaaarkSH
    environment:
      DJANGO_SETTINGS_MODULE: base.settings.base
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["sh", "-c", "./entrypoint.sh"]
